services:
  backend:
    build: /Users/lait-zet/Desktop/Plateforme-de-Traduction-S-curis-e-Fullstack/backend
    env_file:
      - ./backend/.env
    ports:
        - "8000:8000"
  
  frontend:
    build: /Users/lait-zet/Desktop/Plateforme-de-Traduction-S-curis-e-Fullstack/frontend/app
    ports:
        - "3000:3000"

